version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: surekha69-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: offboarding_db
    ports:
      - "5601:5432"
    volumes:
      - pgdata69:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: surekha69-backend
    ports:
      - "3601:3601"
    depends_on:
      - postgres
    environment:
      - PORT=3030
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=offboarding_db
      - DB_HOST=postgres
      - DB_PORT=5432

  employee-offboarding:
    build: ./employee-offboarding
    container_name: surekha69-employee
    ports:
      - "8602:80"
    depends_on:
      - backend

  hr-offboarding:
    build: ./hr-offboarding
    container_name: surekha69-hr
    ports:
      - "8063:80"
    depends_on:
      - backend

volumes:
  pgdata69:

